version: '3.8'

services:
  remix:
    build:
      context: ./reagent-remix-vite
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 24678:24678 # vite hmr
    volumes:
      - ./reagent-remix-vite:/app
      - ./prisma:/app/prisma

      - ./noggin-server/dist/reagent-noggin-shared:/noggin-server/dist/reagent-noggin-shared
      - ./noggin-server/src/reagent-noggin-shared:/noggin-server/src/reagent-noggin-shared
      - ./noggin-server/package.json:/noggin-server/package.json
    environment:
      - DATABASE_URL=postgresql://postgres:pg_dev_password@postgres:5432/postgres?schema=public
      - Y_WEBSOCKET_SERVER_EXTERNAL_URL=ws://localhost:2347
      - NOGGIN_SERVER_EXTERNAL_URL=http://localhost:2358
      - NOGGIN_SERVER_INTERNAL_URL=http://noggin-server:2358
      - OBJECT_STORAGE_INTERNAL_HOST=minio
      - OBJECT_STORAGE_INTERNAL_PORT=9000
      - OBJECT_STORAGE_INTERNAL_USE_SSL=false
      - OBJECT_STORAGE_ACCESS_KEY
      - OBJECT_STORAGE_SECRET_KEY
      - OBJECT_STORAGE_EXTERNAL_URL=http://localhost:9000
    restart: on-failure:5
  yjs-websocket:
    build:
      context: ./y-websocket-server
      dockerfile: Dockerfile.dev
    ports:
      - 2347:2347
    volumes:
      - ./y-websocket-server:/app
      - ./prisma:/app/prisma
    environment:
      - DATABASE_URL=postgresql://postgres:pg_dev_password@postgres:5432/postgres?schema=public
      - SHARED_Y_WEBSOCKET_SERVER_SECRET
    restart: on-failure:5
  noggin-server:
    build:
      context: ./noggin-server
      dockerfile: Dockerfile.dev
    ports:
      - 2358:2358
    volumes:
      - ./noggin-server:/app
      - ./prisma:/app/prisma
    environment:
      - DATABASE_URL=postgresql://postgres:pg_dev_password@postgres:5432/postgres?schema=public
      - Y_WEBSOCKET_SERVER_INTERNAL_URL=http://yjs-websocket:2347
      - SHARED_Y_WEBSOCKET_SERVER_SECRET
      - OBJECT_STORAGE_INTERNAL_HOST=minio
      - OBJECT_STORAGE_INTERNAL_PORT=9000
      - OBJECT_STORAGE_INTERNAL_USE_SSL=false
      - OBJECT_STORAGE_ACCESS_KEY
      - OBJECT_STORAGE_SECRET_KEY
      - OBJECT_STORAGE_EXTERNAL_URL=http://localhost:9000
    restart: on-failure:5
  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: pg_dev_password
      PGDATA: /pg-data
    volumes:
      - ./pg-data:/pg-data
    restart: unless-stopped
  minio:
    image: quay.io/minio/minio
    command: server --console-address ":9001" /data/minio/
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./object-data:/data
      - ./minio:/minio-cfg
    environment:
      MINIO_ROOT_USER: minio_dev_user
      MINIO_ROOT_PASSWORD: minio_dev_password
    restart: unless-stopped
