version: '3.8'

services:
  remix:
    build:
      context: ./reagent-remix-vite
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 24678:24678 # vite hmr
    volumes:
      - ./reagent-remix-vite:/app
      - ./prisma:/app/prisma

      - ./noggin-server/dist/reagent-noggin-shared:/noggin-server/dist/reagent-noggin-shared
      - ./noggin-server/src/reagent-noggin-shared:/noggin-server/src/reagent-noggin-shared
      - ./noggin-server/package.json:/noggin-server/package.json
    environment:
      - DATABASE_URL=postgresql://postgres:pg_dev_password@postgres:5432/postgres?schema=public
      - Y_WEBSOCKET_SERVER_EXTERNAL_URL=ws://localhost:2347
      - NOGGIN_SERVER_EXTERNAL_URL=http://localhost:2358
      - NOGGIN_SERVER_INTERNAL_URL=http://noggin-server:2358
    restart: on-failure:5
  yjs-websocket:
    build:
      context: ./y-websocket-server
      dockerfile: Dockerfile.dev
    ports:
      - 2347:2347
    volumes:
      - ./y-websocket-server:/app
      - ./prisma:/app/prisma
    environment:
      - DATABASE_URL=postgresql://postgres:pg_dev_password@postgres:5432/postgres?schema=public
    restart: on-failure:5
  noggin-server:
    build:
      context: ./noggin-server
      dockerfile: Dockerfile.dev
    ports:
      - 2358:2358
    volumes:
      - ./noggin-server:/app
      - ./prisma:/app/prisma
    environment:
      - DATABASE_URL=postgresql://postgres:pg_dev_password@postgres:5432/postgres?schema=public
    restart: on-failure:5
  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: pg_dev_password
      PGDATA: /pg-data
    volumes:
      - ./pg-data:/pg-data
    restart: unless-stopped
