version: '3.8'

services:
  remix:
    build:
      context: .
      dockerfile: Dockerfile-reagent-remix-vite.prod
    restart: on-failure:5
    environment:
      - REAGENT_EXTERNAL_URL=https://rea.gent
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres?schema=public
      - Y_WEBSOCKET_SERVER_EXTERNAL_URL=wss://ws.rea.gent
      - NOGGIN_SERVER_EXTERNAL_URL=https://noggin.rea.gent
      - NOGGIN_SERVER_EXTERNAL_WEBSOCKET_URL=wss://noggin.rea.gent
      - NOGGIN_SERVER_INTERNAL_URL=http://noggin-server:2358
      - OBJECT_STORAGE_INTERNAL_HOST=minio
      - OBJECT_STORAGE_INTERNAL_PORT=9000
      - OBJECT_STORAGE_INTERNAL_USE_SSL=false
      - OBJECT_STORAGE_ACCESS_KEY
      - OBJECT_STORAGE_SECRET_KEY
      - OBJECT_STORAGE_EXTERNAL_URL=https://objects.rea.gent
      - GITHUB_REDIRECT_URL=https://rea.gent/auth/github/callback

      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - SESSION_SECRET
    depends_on:
      - postgres
      - valkey
  yjs-websocket:
    build:
      context: .
      dockerfile: Dockerfile-y-websocket-server.prod
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres?schema=public
      - SHARED_Y_WEBSOCKET_SERVER_SECRET
    restart: on-failure:5
  noggin-server:
    build:
      context: .
      dockerfile: Dockerfile-noggin-server.prod
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres?schema=public
      - Y_WEBSOCKET_SERVER_INTERNAL_URL=http://yjs-websocket:2347
      - SHARED_Y_WEBSOCKET_SERVER_SECRET
      - OBJECT_STORAGE_INTERNAL_HOST=minio
      - OBJECT_STORAGE_INTERNAL_PORT=9000
      - OBJECT_STORAGE_INTERNAL_USE_SSL=false
      - OBJECT_STORAGE_ACCESS_KEY
      - OBJECT_STORAGE_SECRET_KEY
      - OBJECT_STORAGE_EXTERNAL_URL=https://objects.rea.gent
    restart: on-failure:5
  postgres:
    image: postgres:16.0
    environment:
      - POSTGRES_PASSWORD
      - PGDATA=/pg-data
    volumes:
      - ./pg-data-prod:/pg-data
    restart: unless-stopped
  minio:
    image: quay.io/minio/minio
    command: server --console-address ":9001" /data/minio/
    volumes:
      - ./object-data-prod:/data
      - ./minio:/minio-cfg
    environment:
      - MINIO_ROOT_USER=minio_prod_user
      - MINIO_ROOT_PASSWORD
      - OBJECT_STORAGE_ACCESS_KEY
      - OBJECT_STORAGE_SECRET_KEY
    restart: unless-stopped
  valkey:
    image: valkey/valkey:7.2-alpine
    entrypoint: valkey-server --save 60 1 --loglevel warning
    volumes:
      - ./valkey-data-prod:/data
  caddy:
    image: caddy:2.7.6-alpine
    cap_add:
      - NET_ADMIN
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./caddy-data-prod:/data
      - ./caddy-config-prod:/config
      - ./caddy/Caddyfile.prod:/etc/caddy/Caddyfile
