version: '3.8'

services:
  remix:
    build:
      context: .
      dockerfile: Dockerfile-reagent-remix-vite.prod
    restart: on-failure:5
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres?schema=public
      - Y_WEBSOCKET_SERVER_EXTERNAL_URL=wss://ws.rea.gent
      - NOGGIN_SERVER_EXTERNAL_URL=https://noggin.rea.gent
      - NOGGIN_SERVER_INTERNAL_URL=http://noggin-server:2358
      - OBJECT_STORAGE_INTERNAL_HOST=minio
      - OBJECT_STORAGE_INTERNAL_PORT=9000
      - OBJECT_STORAGE_INTERNAL_USE_SSL=false
      - OBJECT_STORAGE_ACCESS_KEY
      - OBJECT_STORAGE_SECRET_KEY
      - OBJECT_STORAGE_EXTERNAL_URL=https://objects.rea.gent
      - GITHUB_REDIRECT_URL=https://rea.gent/auth/github/callback
      
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - SESSION_SECRET
  postgres:
    image: postgres:16.0
    environment:
      - POSTGRES_PASSWORD
      - PGDATA=/pg-data
    volumes:
      - ./pg-data-prod:/pg-data
    restart: unless-stopped
  yjs-websocket:
    build:
      context: .
      dockerfile: Dockerfile-y-websocket-server.prod
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres?schema=public
      - SHARED_Y_WEBSOCKET_SERVER_SECRET
    restart: on-failure:5
  caddy:
    image: caddy:2.7.6-alpine
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy-data-prod:/data
      - ./caddy-config-prod:/config
      - ./caddy/Caddyfile.prod:/etc/caddy/Caddyfile
